version: '3.8'
services:
  app:
    image: node:20.14.0-alpine3.20
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm install && nohup node login.js"
    ports:
      - 8080:8080
  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
networks:
  default:
    name: app-network
