# .github/workflows/main.yml
name: PrintHelloWorld

on: [push,workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository so we can access the action files
      - name: Checkout repository
        uses: actions/checkout@v2

      # Use the custom action defined in .github/actions/hello-world
      - name: Greet the World
        id: greet
        uses: ./.github/actions/hello-world
        with:
          who-to-greet: 'GitHub Universe'

      # Example of using the output of the custom action
      - name: Get the greeting time
        run: echo "The greeting time was ${{ steps.greet.outputs.time }}"
