name: Build and Deploy 2FA Project

on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  analyze:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Build the project
        run: |
          cd '${{ github.workspace }}/code'
          mvn clean compile

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java
          source-root: '${{ github.workspace }}/code'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'

      # Step 3: Build the project (e.g., using Maven)
      - name: Build with Maven
        run: |
          cd '/home/runner/work/Redback-Capstone-deakin-project/Redback-Capstone-deakin-project/T1_2023/Project 2 2-Factor Authentication (2FA)/code'
          mvn clean package
        env:
          MAVEN_OPTS: -Xmx1024m

      # Step 4: Upload artifact to AWS S3
      - name: Deploy artifact to AWS S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: ""
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_PREFIX }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "/home/runner/work/Redback-Capstone-deakin-project/Redback-Capstone-deakin-project/T1_2023/Project\\ 2\\ 2-Factor\\ Authentication\\ \\(2FA\\)/code/target" # Adjust path to where your .jar/.war is built

