name: Build and Deploy 2FA Project

on:
  push:
  pull_request:
  workflow_dispatch:
jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3
      # Step 2: Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
        # If you wish to specify custom queries, you can do so here or in a config file.
        # By default, queries listed here will override any specified in a config file.
        # Prefix the list here with "+" to use these queries and those in the config file.
          queries: +security-and-quality
      # Step 2: Set up Java environment
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'

      # Step 3: Build the project (e.g., using Maven)
      - name: Build with Maven
        run: |
          cd '${{ github.workspace }}/code'
          mvn clean package
        env:
          MAVEN_OPTS: -Xmx1024m

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        
      # Step 4: Upload artifact to AWS S3
      - name: Deploy artifact to AWS S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: ""
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_PREFIX }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "${{ github.workspace }}/code/target" # Adjust path to where your .jar/.war is built

