name: Node.js Selenium test

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
        options: --network app-network
      app:
        image: node:20.14.0-alpine3.20
        ports:
          - 8080:8080
        options: --network app-network
        volumes:
          - ./:/app
        command: >
          sh -c "cd /app && npm install && nohup node login.js"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run Selenium tests
      run: |
        export SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
        node seleniumTest.js
