name: Node.js Selenium test

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose -y

    - name: Build and run services
      run: |
        docker-compose up -d
        sleep 10  # Wait for services to start

    - name: Run Selenium tests
      run: |
        export SELENIUM_REMOTE_URL=http://localhost:4444/wd/hub
        node seleniumTest.js

    - name: Shutdown services
      if: always()
      run: docker-compose down

