name: secrets&variables
on: 
  push:
  workflow_dispatch:
env:
  Workflow_LEVEL_VAR: 'myworkflow'
jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:20.14.0-alpine3.20
    environment:
      name: dev
    env:
      JOB_LEVEL_VAR: "myjob"


    steps:
      
      - name: Step 1 - Print Job Level Env Variable
        run: |
          echo 'Job-level environment variable: ${{ env.JOB_LEVEL_VAR }}'
          echo "Workflow-level environment variable:  $Workflow_LEVEL_VAR"
          echo 'secrets from the dev environment: ${{ secrets.FAMILY_NAME }}'
          echo 'variables from the dev environment: ${{ vars.NAME }}'
          echo 'Repository secrets: ${{ secrets.PHONE_NUMBER }}'
          echo 'Repository variables: ${{ vars.PROJECT_NAME }}'

      - name: Step 2 - Conditional Logic
        run: |
            if [ "${{ secrets.FAMILY_NAME }}" == "liu" ]; then
              echo "The family name is liu."
            else
              echo "The family name is not liu."
            fi

            if [ "${{ secrets.PHONE_NUMBER }}" == "18970598618" ]; then
              echo "The phone number is 18970598618."
            else
              echo "The phone number is not 18970598618."
            fi
